events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Усі запити, що починаються з /api, йдуть на наш Express сервер
        location /api/ {
            proxy_pass http://api:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Пізніше тут ми додамо налаштування для Next.js клієнта
    }
}